// This file has been generated by TypeSharpGen
import { TriangleImportTestClassA } from "./TriangleImportTestClassA";

export interface TriangleImportTestClassB {
    Dependent: TriangleImportTestClassA;
}
