// This file has been generated by TypeSharpGen
import { TriangleImportTestClassA } from "./TriangleImportTestClassA";
import { TriangleImportTestClassB } from "./TriangleImportTestClassB";

export interface TriangleImportTestClassC {
    DependentA: TriangleImportTestClassA;
    DependentB: TriangleImportTestClassB;
}
