// This file has been generated by TypeSharpGen
import { ImportTestDependencyClass } from "./ImportTestDependencyClass";

export interface ImportTestConsumerClass {
    DependenyProperty: ImportTestDependencyClass;
}
